from dotenv import load_dotenv
from langchain_mistralai import ChatMistralAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableParallel

load_dotenv()

model = ChatMistralAI(model="mistral-small-2506")

parser = StrOutputParser()

code_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a code generator."),
    ("human", "{topic}"),
])

explain_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a senior developer who explains the code to the user."),
    ("human", "{code}"),
])

# seq = code_prompt | model | parser | explain_prompt | model | parser
# response = seq.invoke({"topic": "Write code for palindrome checker in python."})
# we don't save the code generated by the model, we just pass it to the next prompt
# code gets lost
# print(response)

seq_code = code_prompt | model | parser
seq_par = RunnableParallel({
    "code": RunnablePassthrough(),
    "explanation":explain_prompt | model | parser
})

chain = seq_code | seq_par
response = chain.invoke({"topic": "Write code for palindrome checker in python."})
print(response["code"])
print(response["explanation"])